### ISSUE TITLE
Contact e-mail not working

### ISSUE THREAD

**Issue by harrikerko** [MicrosoftDocs/vsts-docs#1451]
Is there some limitations regarding what e-mail is used as contact e-mail? I changed the e-mail recently and now notification messages are no longer sent to the contact e-mail address but the e-mail I use for login is used instead.
Previous contact e-mail address did work. There might be some differences in those two e-mails regarding some subscriptions or who knows what (email that doesn't work does not have any subscriptions)...
I tried to change the e-mail couple times just in case if something didn't go through the first time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c94a78f-77de-a612-1fc8-749518195166
* Version Independent ID: fba4f685-1c59-e1e6-2138-aaa5477e476d
* Content: [Change your email address - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/notifications/change-email-address?view=vsts)
* Content Source: [docs/notifications/change-email-address.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/change-email-address.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by DiscoTrev** [comment]
I am experiencing the same thing. Looks like a bug has been introduced in VSTS somewhere recently resulting in notification messages always being sent to your login email rather than you conta email. I have not recently changed my Contact email address (but it is different to my sign-in email) and as of the 17th July 2018 it was sending notifications to the correct contact email address, but today (1st August 2018) it is now sending notification emails to my sign-in email address rather than my contact email address. A colleague has also confirmed the same affecting them today.

**Comment by elbatk** [comment]
Adding @willsmythe from the product team for awareness, also if you would, please file a bug on the developer community site:
https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by JMFthru** [comment]
I am experiencing the same issue... receiving emails at the sign in the email address as opposed to contact email.

**Comment by caiohn** [comment]
Same here, any workarounds? Because the company changed all the emails, added 3 letter before @ and now no one is receiving e-mails :p

**Comment by ccagahr** [comment]
Same here. Our customer is using work accounts from his *.onmicrosoft.com domain to log in and no one is receaving e-mails because they have their messageboxes on their real domain. Any ideas how to work around this?

**Comment by vanillebear** [comment]
I'm experiencing the same issue... We identified, that the contact-email address is correctly updated within the user profile, but is somehow not synced to the Notification Settings of AzureDevops

**Comment by jcbeck37** [comment]
We are also experiencing this issue for some users in our corporate Azure DevOps network. We recently migrated to use our Active Directory for authentication. Some users migrated without issue, and can correctly modify their Preferred/Contact email, and receive notifications, but others cannot. When they click to the Notifications page, it shows the global / automatic notifications, and their login email is displayed, not their preferred/contact email as it should be.

**Comment by NancyFolsom** [comment]
Is there some resolution for this?

**Comment by harrikerko** [comment]
Contact e-mail started working for me some weeks ago already. Don't know
why or what has changed.

**Comment by ChristopherMank** [comment]
We are still having this issue, even following the fix mentioned above. I do get a confirmation email and confirm it but the notification settings in Azure DevOps still shows old email address.

**Comment by vanillebear** [comment]
Could it be the case that you have personal notification-settings? It worked for me by deleting my personal notification-settings and changing the email address afterwards.

**Comment by elbatk** [comment]
Hi everyone, if you're having an issue with the product, please post your questions on the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). I'll add @willsmythe again for awareness and to let me know if a change or clarification to the docs needs to be made, but going to close this issue here for now as it seems to be a product issue.

**Comment by jcbeck37** [comment]
If anyone else has the issue, please see this open issue in the Azure DevOps Developer Community:

https://developercommunity.visualstudio.com/content/problem/374383/stakeholders-receive-notifications-at-account-emai.html

**Comment by NancyFolsom** [comment]
@ChristopherMank : Did you see this? https://developercommunity.visualstudio.com/content/problem/374383/stakeholders-receive-notifications-at-account-emai.html

My users who had trouble were set up as stakeholders, which we resolved so they have a basic membership (they couldn't see source code). It may be my problem was resolved when we made them basic members, though they also followed the suggestion in https://developercommunity.visualstudio.com/content/problem/28581/cannot-change-contact-e-mail-always-confirmation-p.html. (For any interested listeners, we had to purchase additional licenses. It was very time consuming to track this down and resolve it.) I don't know if this is at all helpful.

**Comment by ChristopherMank** [comment]
Thanks for the info @NancyFolsom. These users do have Basic. I'm going to test again since it did work me when I changed it...

**Comment by jayanthsagar** [comment]
I am also facing same issue. Notifications are not received to updated mail address. It still shows old email address of user in notification subscribers tab.

**Comment by LawrieR** [comment]
As jayanthsagar says, this is totally still an issue. Changing the email address here as described does nothing for the notification email.

**Comment by elbatk** [comment]
I'm pinging @willsmythe here for awareness. Just to be clear, I haven't closed this issue because there isn't an issue, I've closed it as this is a feedback avenue for documentation errors/problems. This issue seems to be a product flaw and should be posted on the Developer Community at https://developercommunity.visualstudio.com/spaces/21/index.html. This is actively monitored by the product team, so you'll be much better off in getting a helpful answer for your issues.

**Comment by jcbeck37** [comment]
Thanks @elbatk 

Again, I believe this open issue is, if not identical, closely related: https://developercommunity.visualstudio.com/content/problem/374383/stakeholders-receive-notifications-at-account-emai.html
